# Generated by Django 4.2.7 on 2025-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_recent_post',
            field=models.BooleanField(default=False, help_text='Marcar como post reciente para mostrar en la página principal'),
        ),
    ]
