# Generated by Django 4.2.7 on 2025-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_is_recent_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Marcar como destacado para mostrar en homepage'),
        ),
    ]
