# Generated by Django 4.2.7 on 2025-07-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogpost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artisan_image',
            field=models.URLField(blank=True, help_text='URL de la foto del artesano', null=True),
        ),
    ]
